version: '3.7' # версия описания docker-compose.yml
services: # описание сервисов, которые развернутся при запуске файла
  jenkins: # развернётся Jenkins
    image: jenkins/jenkins:lts # образ, который скачается для установки Jenkins
    privileged: true
    user: root
    ports: # порты, которые использует сервис
      - 8081:8080 # В контейнере Jenkins развернётся на порте 8080,
        # но на локальной машине этот порт часто занят,
        # поэтому порт 8080 контейнера связывается
        # с портом 8081 на локальной машине.
      # Получится адрес localhost:8081
    container_name: jenkins # имя контейнера: оно может быть любым